# Nuevo archivo Python

# -*- coding: utf-8 -*-
"""handwriting_eprop_with_pen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DIlhyEqSu-BRxM8pXLaFZsca2vc74hjF

# NEST e-prop Handwriting — Training & Analysis

This notebook was generated from your script and split into logical cells: setup, parameters, data loading, network creation, training, and analysis/visualization.
"""

import matplotlib as mpl
import matplotlib.pyplot as plt
import nest
import numpy as np
from cycler import cycler
from IPython.display import Image, display
import os
import pickle
from collections import defaultdict
from sklearn.metrics import mean_squared_error
import os
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
# Try to show schematic if available
try:
    display(Image(filename="./eprop_supervised_regression_schematic_handwriting.png"))
except Exception:
    pass

"""## Parámetros escalables"""

# -------------------------
# 📌 PARÁMETROS ESCALABLES
# -------------------------
# --- al inicio de tu script ---
from mpi4py import MPI
import nest

comm = MPI.COMM_WORLD
rank = comm.Get_rank()

def input_mpi(prompt):
    if rank == 0:
        val = input(prompt)
    else:
        val = None
    val = comm.bcast(val, root=0)
    return val

# Ejemplo de uso:
if rank == 0:
    print("Elige una modalidad:\n1.Variación de carácteres\n2.Generación de carácter\n3.Generación de Abecedario")


# (Opcional) solo imprime desde rank 0 para evitar duplicados:
def print_master(*args, **kwargs):
    if rank == 0:
        print(*args, **kwargs)

rng_seed = 1  # numpy random seed
np.random.seed(rng_seed)  # fix numpy random seed

print("Elige una modalidad:")
print("1.Variación de carácteres")
print("2.Generación de carácter")
print("3.Generación de Abecedario")
tipo_modalidad = int(input_mpi(""))  # <-- ya no habrá EOF en ranks > 0

if tipo_modalidad == 1:
    frecuencia_cambio_letra = 1
    n_iter = 1000
    n_letras_distintas = input("Elija numero de carácteres diferentes:")
    n_estilos_por_letra = input("Elija el número de variaciones.")
    n_estilos = n_letras_distintas * n_estilos_por_letra
    n_batch = n_letras_distintas
    n_base = 280
    n_style = 20
    n_in = 300
    n_rec = 500
    n_out = 3  # number of readout neurons
    n_letras = n_letras_distintas * n_estilos_por_letra

    steps = {
        "data_point": 8,
    }

    """## Cargar letras desde dataset"""

    # -------------------------
    # 📁 CARGAR LETRAS DESDE DATASET
    # -------------------------
    dataset_path = "Dataset_estilos_A/Dataset_AA/prueba"
    trayectorias = sorted([f for f in os.listdir(dataset_path) if f.endswith(".txt")])

    if n_letras > len(trayectorias):
        raise ValueError(f"Solo hay {len(trayectorias)} letras en la carpeta Dataset, pero pediste {n_letras}")

    datos_letras = []
    for i in range(n_letras):
        path_letra = os.path.join(dataset_path, trayectorias[i])
        datos = np.loadtxt(path_letra)
        if datos.ndim != 2 or datos.shape[1] not in (2, 3):
            raise ValueError(f"{trayectorias[i]} debe tener 2 o 3 columnas: (dx, dy[, pen])")
        if datos.shape[1] == 2:
            pen_col = np.ones((datos.shape[0], 1), dtype=datos.dtype)
            datos = np.hstack([datos, pen_col])
        datos_letras.append(datos)

    """## Calcular steps y duraciones"""

    # -------------------------
    # ⚙️ CALCULAR STEPS Y DURACIONES
    # -------------------------
    steps["sequence"] = len(datos_letras[0]) * steps["data_point"]  # asumimos que todas tienen misma longitud
    steps["learning_window"] = steps["sequence"]
    steps["task"] = n_iter * n_batch * steps["sequence"]
    steps.update({
        "offset_gen": 1,
        "delay_in_rec": 1,
        "delay_rec_out": 1,
        "delay_out_norm": 1,
        "extension_sim": 1,
    })
    steps["delays"] = steps["delay_in_rec"] + steps["delay_rec_out"] + steps["delay_out_norm"]
    steps["total_offset"] = steps["offset_gen"] + steps["delays"]
    steps["sim"] = steps["task"] + steps["total_offset"] + steps["extension_sim"]

    duration = {"step": 1.0}
    duration.update({key: value * duration["step"] for key, value in steps.items()})

    params_setup = {
        "eprop_learning_window": duration["learning_window"],
        "eprop_reset_neurons_on_update": True,
        "eprop_update_interval": duration["sequence"],
        "print_time": True,
        "resolution": duration["step"],
        "local_num_threads": 16,
        "rng_seed": rng_seed,
    }

    nest.ResetKernel()
    nest.SetKernelStatus(params_setup)

    tau_m_mean = 30.0  # ms, mean of membrane time constant distribution

    params_nrn_rec = {
        "adapt_tau": 2000.0,  # ms, time constant of adaptive threshold
        "C_m": 250.0,  # pF
        "c_reg": 150.0,  # firing rate regularization scaling
        "E_L": 0.0,  # mV
        "f_target": 20.0,  # spikes/s
        "gamma": 0.3,  # scaling of the pseudo derivative
        "I_e": 0.0,  # pA
        "regular_spike_arrival": False,
        "surrogate_gradient_function": "piecewise_linear",
        "t_ref": 0.0,  # ms
        "tau_m": nest.random.normal(mean=tau_m_mean, std=2.0),  # ms
        "V_m": 0.0,  # mV
        "V_th": 0.03,  # mV
    }
    params_nrn_rec["adapt_beta"] = (
        1.7 * (1.0 - np.exp(-1 / params_nrn_rec["adapt_tau"])) / (1.0 - np.exp(-1.0 / tau_m_mean))
    )  # prefactor of adaptive threshold

    params_nrn_out = {
        "C_m": 1.0,
        "E_L": 0.0,
        "I_e": 0.0,
        "loss": "mean_squared_error",  # loss function
        "regular_spike_arrival": False,
        "tau_m": 50.0,
        "V_m": 0.0,
    }
    params_mm_out = {
        "interval": duration["step"],
        "record_from": ["V_m", "readout_signal", "readout_signal_unnorm", "target_signal", "error_signal"],
        "start": duration["total_offset"],
        "stop": duration["total_offset"] + duration["task"],
    }
    mm_out = nest.Create("multimeter", params=params_mm_out)
    gen_spk_in = nest.Create("spike_generator", n_in)
    nrns_in = nest.Create("parrot_neuron", n_in)
    nrns_rec = nest.Create("eprop_iaf_adapt_bsshslm_2020", n_rec, params_nrn_rec)
    nrns_out = nest.Create("eprop_readout_bsshslm_2020", n_out, params_nrn_out)
    gen_rate_target = nest.Create("step_rate_generator", n_out)

    """## Configurar NEST y crear red"""

    # ====================== OBJETIVOS PARA gen_rate_target (dx, dy, pen) ======================
    # We expect each trajectory to have 3 columns: dx, dy, pen (0/1). If files had 2 cols, pen=1 was added above.
    seq_T = steps["sequence"]
    x_eval = np.arange(seq_T) / steps["data_point"]
    x_data = np.arange(seq_T // steps["data_point"])

    def interp_signal(arr_1d):
        return np.interp(x_eval, x_data, arr_1d)

    dx_all, dy_all, pen_all = [], [], []
    n_sequences = n_iter * n_batch
    # Asegurar que existe el plan de (letra, estilo) ANTES de construir los objetivos
    if 'letras_estilos_por_secuencia' not in globals():
        combinaciones = [(l, s) for l in range(n_letras_distintas) for s in range(n_estilos_por_letra)]
        repeticiones = int(np.ceil(n_sequences / len(combinaciones)))
        combinaciones_replicadas = (combinaciones * repeticiones)[:n_sequences]
        letras_estilos_por_secuencia = np.array(combinaciones_replicadas)

    for i in range(n_sequences):
        letra_idx, estilo_idx = letras_estilos_por_secuencia[i]
        # Mapear de forma robusta por si hay menos trayectorias que estilos
        traj_idx = (letra_idx * n_estilos_por_letra + estilo_idx) % len(datos_letras)

        raw = datos_letras[traj_idx]  # (T_points, 3)
        dx_cum = np.cumsum(raw[:, 0])
        dy_cum = np.cumsum(raw[:, 1])
        # normalize and anchor
        if np.max(np.abs(dx_cum)) > 0: dx_cum = dx_cum / np.max(np.abs(dx_cum))
        dx_cum = dx_cum - dx_cum[0]
        if np.max(np.abs(dy_cum)) > 0: dy_cum = dy_cum / np.max(np.abs(dy_cum))
        dy_cum = dy_cum - dy_cum[0]
        pen_seq = raw[:, 2].astype(float)

        dx_all.append(interp_signal(dx_cum))
        dy_all.append(interp_signal(dy_cum))
        # keep pen in [0,1] after interpolation
        pen_all.append(np.clip(np.interp(x_eval, x_data, pen_seq), 0.0, 1.0))

    full_dx  = np.concatenate(dx_all).astype(np.float32)
    full_dy  = np.concatenate(dy_all).astype(np.float32)
    full_pen = np.concatenate(pen_all).astype(np.float32)

    amp_times = np.arange(0.0, duration["task"], duration["step"]) + duration["total_offset"]

    params_gen_rate_target = [
        {"amplitude_times": amp_times, "amplitude_values": full_dx},
        {"amplitude_times": amp_times, "amplitude_values": full_dy},
        {"amplitude_times": amp_times, "amplitude_values": full_pen},
    ]
    nest.SetStatus(gen_rate_target, params_gen_rate_target)

    # final spike to force update
    gen_spk_final_update = nest.Create("spike_generator", 1, {"spike_times": [duration["task"] + duration["delays"]]})
    nest.Connect(gen_spk_final_update, nrns_in + nrns_rec, "all_to_all", {"weight": 1000.0})

    """## Definir conexiones y pesos iniciales"""

    params_conn_all_to_all = {"rule": "all_to_all", "allow_autapses": False}
    params_conn_one_to_one = {"rule": "one_to_one"}

    dtype_weights = np.float32
    weights_in_rec = np.array(np.random.randn(n_in, n_rec).T / np.sqrt(n_in), dtype=dtype_weights)
    weights_rec_rec = np.array(np.random.randn(n_rec, n_rec).T / np.sqrt(n_rec), dtype=dtype_weights)
    np.fill_diagonal(weights_rec_rec, 0.0)  # no autapses
    weights_rec_out = np.array(np.random.randn(n_rec, n_out).T / np.sqrt(n_rec), dtype=dtype_weights)
    weights_out_rec = np.array(np.random.randn(n_rec, n_out) / np.sqrt(n_rec), dtype=dtype_weights)

    params_common_syn_eprop = {
        "optimizer": {
            "type": "adam",
            "batch_size": n_batch,
            "beta_1": 0.9,
            "beta_2": 0.999,
            "epsilon": 1e-8,
            "eta": 5e-3,
            "Wmin": -100.0,
            "Wmax": 100.0,
        },
        "average_gradient": False,
    }
    params_syn_base = {
        "synapse_model": "eprop_synapse_bsshslm_2020",
        "delay": duration["step"],  # ms
        "tau_m_readout": params_nrn_out["tau_m"],
    }
    params_syn_in = params_syn_base.copy()
    params_syn_in["weight"] = weights_in_rec
    params_syn_rec = params_syn_base.copy()
    params_syn_rec["weight"] = weights_rec_rec
    params_syn_out = params_syn_base.copy()
    params_syn_out["weight"] = weights_rec_out

    params_syn_feedback = {
        "synapse_model": "eprop_learning_signal_connection_bsshslm_2020",
        "delay": duration["step"],
        "weight": weights_out_rec,
    }
    params_syn_rate_target = {
        "synapse_model": "rate_connection_delayed",
        "delay": duration["step"],
        "receptor_type": 2,
    }
    params_syn_static = {
        "synapse_model": "static_synapse",
        "delay": duration["step"],
    }
    params_init_optimizer = {
        "optimizer": {
            "m": 0.0,
            "v": 0.0,
        }
    }

    nest.SetDefaults("eprop_synapse_bsshslm_2020", params_common_syn_eprop)

    nest.Connect(gen_spk_in, nrns_in, params_conn_one_to_one, params_syn_static)   # 1
    nest.Connect(nrns_in, nrns_rec, params_conn_all_to_all, params_syn_in)         # 2
    nest.Connect(nrns_rec, nrns_rec, params_conn_all_to_all, params_syn_rec)       # 3
    nest.Connect(nrns_rec, nrns_out, params_conn_all_to_all, params_syn_out)       # 4
    nest.Connect(nrns_out, nrns_rec, params_conn_all_to_all, params_syn_feedback)  # 5
    nest.Connect(gen_rate_target, nrns_out, params_conn_one_to_one, params_syn_rate_target)  # 6
    nest.Connect(mm_out, nrns_out)

    # After creating the connections, initialize optimizer dyn vars for a couple of connections
    conns = nest.GetConnections(nrns_rec[0], nrns_rec[1:3])
    if len(conns) > 0:
        nest.SetStatus(conns, [params_init_optimizer] * len(conns))

    """## Generar entradas (base + estilo con jitter)"""

    # ====================== ENTRADAS (BASE + ESTILO CON JITTER) ======================
    # Recalcular para asegurar consistencia si se cambia n_base/n_style
    n_in = n_base + n_style
    assert n_base + n_style == n_in, f"El total de neuronas ({n_base} + {n_style}) debe ser igual a n_in ({n_in})"

    input_spike_prob = 0.05
    n_sequences = n_iter * n_batch
    dtype_in_spks = np.float32

    def generar_spikes_entrenamiento():
        def jitter_spike_train(base_spikes, window=10):
            n_neu, T = base_spikes.shape
            out = np.zeros_like(base_spikes, dtype=bool)
            for i in range(n_neu):
                idx = np.flatnonzero(base_spikes[i])
                if idx.size == 0:
                    continue
                shifts = np.random.randint(-window, window + 1, size=idx.size)
                new_idx = np.clip(idx + shifts, 0, T - 1)
                out[i, new_idx] = True
            out[:, 0] = False
            return out

        ventana_jitter = 10

        spikes_base_por_letra = []
        spikes_por_estilo = {}

        # base por letra (n_base)
        for letra_idx in range(n_letras_distintas):
            np.random.seed(42 + letra_idx)
            spike_train_base = (np.random.rand(n_base, steps["sequence"]) < input_spike_prob)
            spike_train_base[0, :] = 0
            spikes_base_por_letra.append(spike_train_base)

        # estilos (n_style): estilo 0 aleatorio; estilo 1.. = jitter del 0
        for letra_idx in range(n_letras_distintas):
            seed_base = 100 + letra_idx
            np.random.seed(seed_base)
            estilo0 = (np.random.rand(n_style, steps["sequence"]) < input_spike_prob)
            estilo0[0, :] = 0
            spikes_por_estilo[letra_idx * n_estilos_por_letra + 0] = estilo0

            for estilo_idx in range(1, n_estilos_por_letra):
                seed_jitter = 200 + letra_idx + 1000 * estilo_idx
                np.random.seed(seed_jitter)
                estilo_derivado = jitter_spike_train(estilo0, window=ventana_jitter)
                estilo_derivado[0, :] = 0
                spikes_por_estilo[letra_idx * n_estilos_por_letra + estilo_idx] = estilo_derivado

        return spikes_base_por_letra, spikes_por_estilo

    # Genera spikes de entrenamiento (reproducibles)
    spikes_base_por_letra, spikes_por_estilo = generar_spikes_entrenamiento()

    # Asignar combinaciones (letra_idx, estilo_idx) por secuencia
    combinaciones = [(l, s) for l in range(n_letras_distintas) for s in range(n_estilos_por_letra)]
    repeticiones = int(np.ceil(n_sequences / len(combinaciones)))
    combinaciones_replicadas = (combinaciones * repeticiones)[:n_sequences]
    letras_estilos_por_secuencia = np.array(combinaciones_replicadas)

    # Guardar orden
    os.makedirs("output_estilos", exist_ok=True)
    np.save("output_estilos/letras_estilos_por_secuencia.npy", letras_estilos_por_secuencia)

    # Construir booleano (n_in, n_sequences*T) con base+estilo
    input_spike_bools_concat = []
    for seq_idx in range(n_sequences):
        letra_idx, estilo_idx = letras_estilos_por_secuencia[seq_idx]
        estilo_global_idx = letra_idx * n_estilos_por_letra + estilo_idx
        spike_train_base = spikes_base_por_letra[letra_idx]
        estilo_spikes = spikes_por_estilo[estilo_global_idx]
        spikes_concat = np.vstack([spike_train_base, estilo_spikes])
        input_spike_bools_concat.append(spikes_concat)
    input_spike_bools_concat = np.concatenate(input_spike_bools_concat, axis=1)
    os.makedirs("output_estilos", exist_ok=True)

    # Con n_letras_distintas = 1 y n_estilos_por_letra = 2:
    #   - base de la letra 0
    #   - estilo A1 = spikes_por_estilo[0]
    #   - estilo A2 = spikes_por_estilo[1]  (jitter del A1)
    np.save("output_estilos/base_letter0.npy",  spikes_base_por_letra[0].astype(np.uint8))
    np.save("output_estilos/style_A1.npy",      spikes_por_estilo[0].astype(np.uint8))
    #np.save("output_estilos/style_A2.npy",      spikes_por_estilo[1].astype(np.uint8))

    # Generar spike_times para spike_generator
    spike_times_global = np.arange(duration["step"], duration["task"], duration["step"]) + duration["offset_gen"]
    input_spike_bools_concat_no_t0 = input_spike_bools_concat[:, 1:]  # quitar t=0

    params_gen_spk_in = []
    for input_spike_bool in input_spike_bools_concat_no_t0:
        input_spike_times = spike_times_global[input_spike_bool]
        params_gen_spk_in.append({"spike_times": input_spike_times.astype(dtype_in_spks)})

    nest.SetStatus(gen_spk_in, params_gen_spk_in)

    """## Utilidad: extracción de matrices de pesos"""

    def get_weights(pop_pre, pop_post):
        conns = nest.GetConnections(pop_pre, pop_post).get(["source", "target", "weight"])
        conns["senders"] = np.array(conns["source"]) - np.min(conns["source"])
        conns["targets"] = np.array(conns["target"]) - np.min(conns["target"])
        conns["weight_matrix"] = np.zeros((len(pop_post), len(pop_pre)))
        conns["weight_matrix"][conns["targets"], conns["senders"]] = conns["weight"]
        return conns

    """## Simulación"""

    # ====================== SIMULACIÓN ======================
    nest.Simulate(duration["sim"])

    weights_post_train = {
        "in_rec": get_weights(nrns_in, nrns_rec),
        "rec_rec": get_weights(nrns_rec, nrns_rec),
        "rec_out": get_weights(nrns_rec, nrns_out),
    }

    """## Análisis de señales y pérdidas"""

    # ====================== ANÁLISIS ======================
    os.makedirs("output_estilos", exist_ok=True)

    events_mm_out = mm_out.get("events")
    readout_signal = events_mm_out["readout_signal"]
    target_signal  = events_mm_out["target_signal"]
    senders        = events_mm_out["senders"]

    sender_ids = sorted(np.unique(senders))  # expect 3: dx, dy, pen
    readouts = [readout_signal[senders == sid] for sid in sender_ids]
    targets  = [target_signal[senders == sid] for sid in sender_ids]
    # Alias útiles para dx/dy
    readout_0, readout_1 = readouts[0], readouts[1]
    target_0, target_1   = targets[0], targets[1]

    seq_len = steps["sequence"]
    n_sequences = n_iter * n_batch

    # loss per channel and total
    loss_list = []
    for sid in sender_ids:
        idc = senders == sid
        error = (readout_signal[idc] - target_signal[idc]) ** 2
        loss_list.append(0.5 * np.add.reduceat(error, np.arange(0, steps["task"], steps["sequence"])))
    loss = np.sum(loss_list, axis=0)

    fig, ax = plt.subplots()
    if len(loss_list) >= 1: ax.plot(range(1, len(loss_list[0])+1), loss_list[0], label="E0", alpha=0.7, ls="--")
    if len(loss_list) >= 2: ax.plot(range(1, len(loss_list[1])+1), loss_list[1], label="E1", alpha=0.7, ls=":")
    ax.plot(range(1, len(loss)+1), loss, label="E total")
    ax.set_xlabel("training iteration"); ax.set_ylabel("loss"); ax.legend(bbox_to_anchor=(1.01,0.5), loc="center left")
    fig.tight_layout(); plt.savefig("output_estilos/loss_training.png", dpi=300); plt.close()

    # MSE per channel
    from sklearn.metrics import mean_squared_error
    y_dx, y_dy, y_pen = readouts[:3]
    t_dx, t_dy, t_pen = targets[:3]
    print("MSE dx={:.6f} dy={:.6f} pen={:.6f}".format(
        mean_squared_error(t_dx, y_dx),
        mean_squared_error(t_dy, y_dy),
        mean_squared_error(t_pen, y_pen),
    ))

    # Plot last sequence with pen mask
    last_start = (n_sequences - 1) * seq_len
    last_end   = last_start + seq_len
    mask_r = y_pen[last_start:last_end] >= 0.5
    mask_t = t_pen[last_start:last_end] >= 0.5

    xr = np.where(mask_r, y_dx[last_start:last_end], np.nan)
    yr = np.where(mask_r, -y_dy[last_start:last_end], np.nan)
    xt = np.where(mask_t,  t_dx[last_start:last_end], np.nan)
    yt = np.where(mask_t,  -t_dy[last_start:last_end], np.nan)

    plt.figure(figsize=(6,3))
    plt.plot(xr, yr, label="readout")
    plt.plot(xt, yt, label="target", alpha=0.7)
    plt.axis("equal"); plt.axis("off"); plt.legend(); plt.tight_layout()
    plt.savefig("output_estilos/trajectory_last_with_pen.png", dpi=300)
    plt.show()

    """## Métricas por combinación letra-estilo y trayectorias"""

    # ✅ Cargar combinaciones (letra, estilo) por secuencia
    letras_estilos_por_secuencia = np.load("output_estilos/letras_estilos_por_secuencia.npy")

    # 🗂️ Agrupar secuencias por (letra_idx, estilo_idx)
    secuencias_por_letra_estilo = defaultdict(list)
    for i, (letra_idx, estilo_idx) in enumerate(letras_estilos_por_secuencia):
        secuencias_por_letra_estilo[(letra_idx, estilo_idx)].append(i)

    # --- Detectar canal PEN (0/1) y reasignar alias dx/dy/pen ---
    def _detect_pen_channel(_targets):
        best, idx = -1.0, 0
        for k in range(min(3, len(_targets))):
            v = np.asarray(_targets[k])
            # Puntuación alta si está en [0,1] y pegado a 0 o 1
            in01 = np.mean((v >= -1e-6) & (v <= 1.0 + 1e-6))
            binish = np.mean((np.isclose(v, 0.0, atol=1e-3)) | (np.isclose(v, 1.0, atol=1e-3)))
            score = 0.7 * binish + 0.3 * in01
            if score > best:
                best, idx = score, k
        return idx

    pen_idx = _detect_pen_channel(targets)
    other_idx = [i for i in range(3) if i != pen_idx]

    y_pen, t_pen = readouts[pen_idx], targets[pen_idx]
    y_dx,  y_dy  = readouts[other_idx[0]], readouts[other_idx[1]]
    t_dx,  t_dy  = targets[other_idx[0]], targets[other_idx[1]]

    print(f"Canal PEN detectado: {pen_idx} (dx, dy -> {other_idx})")

    seq_len = steps["sequence"]
    n_sequences = n_iter * n_batch

    print("\n📊 MSE por combinación letra-estilo (solo pen-down):")
    for (letra_idx, estilo_idx), indices in secuencias_por_letra_estilo.items():
        last_idx = indices[-1]
        start = last_idx * seq_len
        end   = start + seq_len
        m = (t_pen[start:end] >= 0.5)  # pen-down
        # Si por alguna razón no hay pen-down en esa secuencia, cae a todo el segmento
        if not np.any(m):
            m = slice(None)
        mse_x = mean_squared_error(t_dx[start:end][m], y_dx[start:end][m])
        mse_y = mean_squared_error(t_dy[start:end][m], y_dy[start:end][m])
        mse_total = (mse_x + mse_y) / 2
        print(f" - Letra {letra_idx}, Estilo {estilo_idx}: MSE_X={mse_x:.6f}, MSE_Y={mse_y:.6f}, MSE={mse_total:.6f}")

    # 📊 Visualizar última trayectoria aprendida de cada estilo (solo pen-down)
    letra_idx = 0
    estilos_disponibles = sorted({e for (l, e) in secuencias_por_letra_estilo.keys() if l == letra_idx})
    if len(estilos_disponibles) == 0:
        print("No hay estilos disponibles para visualizar.")
    else:
        fig, axs = plt.subplots(1, len(estilos_disponibles), figsize=(4*len(estilos_disponibles), 4))
        if len(estilos_disponibles) == 1:
            axs = [axs]
        for i, estilo_idx in enumerate(estilos_disponibles):
            seqs = secuencias_por_letra_estilo.get((letra_idx, estilo_idx), [])
            if not seqs:
                continue
            seq_id = seqs[-1]
            start = seq_id * seq_len
            end   = start + seq_len
            mR = (y_pen[start:end] >= 0.5)
            axs[i].plot(np.where(mR, y_dx[start:end], np.nan),
                        np.where(mR, -y_dy[start:end], np.nan))
            axs[i].set_title(f"Estilo A{estilo_idx+1}")
            axs[i].axis("equal"); axs[i].axis("off")
        plt.tight_layout(); plt.show()

    """## Guardar modelo y visualizaciones finales"""

    # ====================== GUARDAR MODELO Y VISUALIZACIONES ======================
    output_folder = "interpolacion"
    os.makedirs(output_folder, exist_ok=True)

    modelo = {
        "pesos_in_rec": weights_post_train["in_rec"]["weight_matrix"],
        "pesos_rec_rec": weights_post_train["rec_rec"]["weight_matrix"],
        "pesos_rec_out": weights_post_train["rec_out"]["weight_matrix"],
        "n_in": n_in,
        "n_rec": n_rec,
        "n_out": n_out,
        "duration": duration,
        "steps": steps,
    }
    ruta_modelo = "interpolacion/interpolacion.pkl"
    with open(ruta_modelo, "wb") as f:
        pickle.dump(modelo, f)
    print(f"✅ Modelo guardado en: {ruta_modelo}")

    # Leer outputs y secuencia (otra vez, ya consolidado)
    events = mm_out.get("events")
    senders2 = events["senders"]
    sender_ids2 = sorted(np.unique(senders2))
    readout_0b = np.array(events["readout_signal"][senders2 == sender_ids2[0]]).ravel()
    readout_1b = np.array(events["readout_signal"][senders2 == sender_ids2[1]]).ravel()
    target_0b  = np.array(events["target_signal"][senders2 == sender_ids2[0]]).ravel()
    target_1b  = np.array(events["target_signal"][senders2 == sender_ids2[1]]).ravel()

    letras_estilos_por_secuencia = np.load("output_estilos/letras_estilos_por_secuencia.npy")
    seq_len = steps["sequence"]

    # Agrupar últimas trayectorias por estilo
    secuencias_por_estilo = defaultdict(list)
    for i, (letra, estilo) in enumerate(letras_estilos_por_secuencia):
        secuencias_por_estilo[estilo].append(i)

    # Visualizar y guardar
    output_dir = "interpolacion"
    os.makedirs(output_dir, exist_ok=True)

    for estilo_idx in [0, 1]:
        last_seq_idx = secuencias_por_estilo[estilo_idx][-1]
        start = last_seq_idx * seq_len
        end = start + seq_len

        r0 = readout_0b[start:end]
        r1 = readout_1b[start:end]
        t0 = target_0b[start:end]
        t1 = target_1b[start:end]

        mse_x = mean_squared_error(t0, r0)
        mse_y = mean_squared_error(t1, r1)

        estilo_name = f"A{estilo_idx + 1}"
        fig, ax = plt.subplots(figsize=(6, 3))
        ax.plot(r0, -r1, label="readout", color="red")
        ax.plot(t0, -t1, label="target", color="blue")
        ax.set_title(f"Letra A estilo {estilo_name}\nMSE X: {mse_x:.4f} | Y: {mse_y:.4f}")
        ax.axis("equal")
        ax.axis("off")
        ax.legend()
        plt.tight_layout()
        plt.savefig(f"{output_dir}/A_{estilo_name}.png", dpi=300)
        plt.close()

    print("✅ Visualizaciones guardadas en la carpeta 'interpolacion'")
#################################################################
#################################################################
#################################################################
#====================ABECEDARIO==================================
#################################################################
#################################################################
#################################################################
elif tipo_modalidad == 3:
    frecuencia_cambio_letra = 1
    n_iter = 1000
    n_batch = 1
    n_letras= 3
    n_in = 200
    n_rec = 400
    n_out = 3  # number of readout neurons
    # CARGAR EL DATASET
    
    steps = {
        "data_point": 8
    }
    dataset_path = "/home/gerardasbert/Desktop/Master/TFM/snn_marc/input_characters"
    trayectorias = sorted([f for f in os.listdir(dataset_path) if f.endswith(".txt")])
    if n_letras > len(trayectorias):
        raise ValueError(f"Solo hay {len(trayectorias)} letras en la carpeta Dataset, pero pediste {n_letras}")

    datos_letras = []
    for i in range(n_letras):
        path_letra = os.path.join(dataset_path, trayectorias[i])
        datos = np.loadtxt(path_letra)
        if datos.ndim != 2 or datos.shape[1] not in (2, 3):
            raise ValueError(f"{trayectorias[i]} debe tener 2 o 3 columnas: (dx, dy[, pen])")
        if datos.shape[1] == 2:
            pen_col = np.ones((datos.shape[0], 1), dtype=datos.dtype)
            datos = np.hstack([datos, pen_col])
        datos_letras.append(datos)
    # -------------------------
    # ⚙️ CALCULAR STEPS Y DURACIONES
    # -------------------------
    steps["sequence"] = len(datos_letras[0]) * steps["data_point"]  # asumimos que todas tienen misma longitud
    steps["learning_window"] = steps["sequence"]
    steps["task"] = n_iter * n_batch * steps["sequence"]
    steps.update({
        "offset_gen": 1,
        "delay_in_rec": 1,
        "delay_rec_out": 1,
        "delay_out_norm": 1,
        "extension_sim": 1,
    })
    steps["delays"] = steps["delay_in_rec"] + steps["delay_rec_out"] + steps["delay_out_norm"]
    steps["total_offset"] = steps["offset_gen"] + steps["delays"]
    steps["sim"] = steps["task"] + steps["total_offset"] + steps["extension_sim"]

    duration = {"step": 1.0}
    duration.update({key: value * duration["step"] for key, value in steps.items()})

    params_setup = {
        "eprop_learning_window": duration["learning_window"],
        "eprop_reset_neurons_on_update": True,
        "eprop_update_interval": duration["sequence"],
        "print_time": True,
        "resolution": duration["step"],
        "local_num_threads": 16,
       "total_num_virtual_procs": 16,
        "rng_seed": rng_seed,
    }

    nest.ResetKernel()
    nest.SetKernelStatus(params_setup)

    tau_m_mean = 30.0  # ms, mean of membrane time constant distribution

    params_nrn_rec = {
        "adapt_tau": 2000.0,  # ms, time constant of adaptive threshold
        "C_m": 250.0,  # pF
        "c_reg": 150.0,  # firing rate regularization scaling
        "E_L": 0.0,  # mV
        "f_target": 20.0,  # spikes/s
        "gamma": 0.3,  # scaling of the pseudo derivative
        "I_e": 0.0,  # pA
        "regular_spike_arrival": False,
        "surrogate_gradient_function": "piecewise_linear",
        "t_ref": 0.0,  # ms
        "tau_m": nest.random.normal(mean=tau_m_mean, std=2.0),  # ms
        "V_m": 0.0,  # mV
        "V_th": 0.03,  # mV
    }
    params_nrn_rec["adapt_beta"] = (
        1.7 * (1.0 - np.exp(-1 / params_nrn_rec["adapt_tau"])) / (1.0 - np.exp(-1.0 / tau_m_mean))
    )  # prefactor of adaptive threshold

    params_nrn_out = {
        "C_m": 1.0,
        "E_L": 0.0,
        "I_e": 0.0,
        "loss": "mean_squared_error",  # loss function
        "regular_spike_arrival": False,
        "tau_m": 50.0,
        "V_m": 0.0,
    }
    params_mm_out = {
        "interval": duration["step"],
        "record_from": ["V_m", "readout_signal", "readout_signal_unnorm", "target_signal", "error_signal"],
        "start": duration["total_offset"],
        "stop": duration["total_offset"] + duration["task"],
    }
    mm_out = nest.Create("multimeter", params=params_mm_out)
    gen_spk_in = nest.Create("spike_generator", n_in)
    nrns_in = nest.Create("parrot_neuron", n_in)
    nrns_rec = nest.Create("eprop_iaf_adapt_bsshslm_2020", n_rec, params_nrn_rec)
    nrns_out = nest.Create("eprop_readout_bsshslm_2020", n_out, params_nrn_out)
    gen_rate_target = nest.Create("step_rate_generator", n_out)

    """## Configurar NEST y crear red"""

    # ====================== OBJETIVOS PARA gen_rate_target (dx, dy, pen) ======================
    # Soportamos ficheros con 2 columnas (dx,dy) o 3 (dx,dy,pen). Si faltase pen, pen=1.
    seq_T = steps["sequence"]
    x_eval = np.arange(seq_T) / steps["data_point"]
    x_data = np.arange(seq_T // steps["data_point"])

    def interp_signal(arr_1d):
        return np.interp(x_eval, x_data, arr_1d)

    dx_all, dy_all, pen_all = [], [], []
    n_sequences = n_iter * n_batch

    # 🔁 Plan de letras: 0..(n_letras-1) repetido hasta cubrir todas las secuencias
    letras_por_secuencia = np.resize(np.arange(n_letras), n_sequences)

    for i in range(n_sequences):
        letra_idx = int(letras_por_secuencia[i])

        raw = datos_letras[letra_idx]  # (T_points, 2|3) -> dx, dy[, pen]
        # dx,dy acumulados (coordenadas)
        dx_cum = np.cumsum(raw[:, 0].astype(float))
        dy_cum = np.cumsum(raw[:, 1].astype(float))

        # normalizar y anclar al origen
        if np.max(np.abs(dx_cum)) > 0:
            dx_cum = dx_cum / np.max(np.abs(dx_cum))
        dx_cum = dx_cum - dx_cum[0]
        if np.max(np.abs(dy_cum)) > 0:
            dy_cum = dy_cum / np.max(np.abs(dy_cum))
        dy_cum = dy_cum - dy_cum[0]

        # pen: si el fichero no trae 3ª columna, asumimos pen=1 (todo pen-down)
        if raw.shape[1] >= 3:
            pen_seq = raw[:, 2].astype(float)
        else:
            pen_seq = np.ones(raw.shape[0], dtype=float)

        dx_all.append(interp_signal(dx_cum))
        dy_all.append(interp_signal(dy_cum))
        # Mantener pen en [0,1] tras la interpolación
        pen_all.append(np.clip(np.interp(x_eval, x_data, pen_seq), 0.0, 1.0))

    full_dx  = np.concatenate(dx_all).astype(np.float32)
    full_dy  = np.concatenate(dy_all).astype(np.float32)
    full_pen = np.concatenate(pen_all).astype(np.float32)

    amp_times = np.arange(0.0, duration["task"], duration["step"]) + duration["total_offset"]

    params_gen_rate_target = [
        {"amplitude_times": amp_times, "amplitude_values": full_dx},
        {"amplitude_times": amp_times, "amplitude_values": full_dy},
        {"amplitude_times": amp_times, "amplitude_values": full_pen},
    ]
    nest.SetStatus(gen_rate_target, params_gen_rate_target)

    # 🔚 Spike final para forzar actualización del optimizador
    gen_spk_final_update = nest.Create("spike_generator", 1, {"spike_times": [duration["task"] + duration["delays"]]})
    nest.Connect(gen_spk_final_update, nrns_in + nrns_rec, "all_to_all", {"weight": 1000.0})

    """## Definir conexiones y pesos iniciales"""

    params_conn_all_to_all = {"rule": "all_to_all", "allow_autapses": False}
    params_conn_one_to_one = {"rule": "one_to_one"}

    dtype_weights = np.float32
    weights_in_rec = np.array(np.random.randn(n_in, n_rec).T / np.sqrt(n_in), dtype=dtype_weights)
    weights_rec_rec = np.array(np.random.randn(n_rec, n_rec).T / np.sqrt(n_rec), dtype=dtype_weights)
    np.fill_diagonal(weights_rec_rec, 0.0)  # no autapses
    weights_rec_out = np.array(np.random.randn(n_rec, n_out).T / np.sqrt(n_rec), dtype=dtype_weights)
    weights_out_rec = np.array(np.random.randn(n_rec, n_out) / np.sqrt(n_rec), dtype=dtype_weights)

    params_common_syn_eprop = {
        "optimizer": {
            "type": "adam",
            "batch_size": n_batch,
            "beta_1": 0.9,
            "beta_2": 0.999,
            "epsilon": 1e-8,
            "eta": 5e-3,
            "Wmin": -100.0,
            "Wmax": 100.0,
        },
        "average_gradient": False,
    }
    params_syn_base = {
        "synapse_model": "eprop_synapse_bsshslm_2020",
        "delay": duration["step"],  # ms
        "tau_m_readout": params_nrn_out["tau_m"],
    }
    params_syn_in = params_syn_base.copy()
    params_syn_in["weight"] = weights_in_rec
    params_syn_rec = params_syn_base.copy()
    params_syn_rec["weight"] = weights_rec_rec
    params_syn_out = params_syn_base.copy()
    params_syn_out["weight"] = weights_rec_out

    params_syn_feedback = {
        "synapse_model": "eprop_learning_signal_connection_bsshslm_2020",
        "delay": duration["step"],
        "weight": weights_out_rec,
    }
    params_syn_rate_target = {
        "synapse_model": "rate_connection_delayed",
        "delay": duration["step"],
        "receptor_type": 2,
    }
    params_syn_static = {
        "synapse_model": "static_synapse",
        "delay": duration["step"],
    }
    params_init_optimizer = {
        "optimizer": {
            "m": 0.0,
            "v": 0.0,
        }
    }

    nest.SetDefaults("eprop_synapse_bsshslm_2020", params_common_syn_eprop)

    nest.Connect(gen_spk_in, nrns_in, params_conn_one_to_one, params_syn_static)   # 1
    nest.Connect(nrns_in, nrns_rec, params_conn_all_to_all, params_syn_in)         # 2
    nest.Connect(nrns_rec, nrns_rec, params_conn_all_to_all, params_syn_rec)       # 3
    nest.Connect(nrns_rec, nrns_out, params_conn_all_to_all, params_syn_out)       # 4
    nest.Connect(nrns_out, nrns_rec, params_conn_all_to_all, params_syn_feedback)  # 5
    nest.Connect(gen_rate_target, nrns_out, params_conn_one_to_one, params_syn_rate_target)  # 6
    nest.Connect(mm_out, nrns_out)

    conns = nest.GetConnections(nrns_rec[0], nrns_rec[1:3])
    if len(conns) > 0:
        nest.SetStatus(conns, [params_init_optimizer] * len(conns))

    """## Generar entradas (base + estilo con jitter)"""

    # ====================== ENTRADAS (UN SPIKETRAIN POR LETRA) ======================

    input_spike_prob = 0.05          # probabilidad de spike por neurona y paso
    n_sequences = n_iter * n_batch
    dtype_in_spks = np.float32

    # 🔁 Spike trains "congelados" por letra (reproducibles)
    #    Para cada letra l generamos una matriz booleana (n_in, steps["sequence"])
    #    con disparos Bernoulli independientes; semilla distinta por letra.
    spikes_por_letra = {}
    for letra_idx in range(n_letras):
        rng = np.random.RandomState(1000 + letra_idx)
        # (n_in, T)
        spikes = rng.rand(n_in, steps["sequence"]) < input_spike_prob
        # evitar spikes en t=0 para dispositivos
        spikes[:, 0] = False
        spikes_por_letra[letra_idx] = spikes

    # 🧠 Plan de letras por secuencia: 0..(n_letras-1) repitiendo, con frecuencia_cambio_letra
    letras_por_secuencia = np.array([
        (i // frecuencia_cambio_letra) % n_letras
        for i in range(n_sequences)
    ], dtype=int)

    # (Opcional) Guardar el plan para análisis posteriores (segunda columna = 0 por compatibilidad)
    os.makedirs("output_estilos", exist_ok=True)
    np.save("output_estilos/letras_estilos_por_secuencia.npy",
            np.stack([letras_por_secuencia, np.zeros_like(letras_por_secuencia)], axis=1))

    # ⛓️‍➡️ Concatenar horizontalmente las secuencias elegidas
    #     Resultado: (n_in, n_sequences * steps["sequence"])
    input_spike_bools_concat = np.concatenate(
        [spikes_por_letra[int(letra_idx)] for letra_idx in letras_por_secuencia],
        axis=1
    )

    # 🕒 Generar spike_times con offset correcto y cargar en spike_generator
    spike_times_global = np.arange(duration["step"], duration["task"], duration["step"]) + duration["offset_gen"]
    input_spike_bools_concat_no_t0 = input_spike_bools_concat[:, 1:]  # quitar t=0 global

    params_gen_spk_in = []
    for row in input_spike_bools_concat_no_t0:
        input_spike_times = spike_times_global[row]
        params_gen_spk_in.append({"spike_times": input_spike_times.astype(dtype_in_spks)})

    nest.SetStatus(gen_spk_in, params_gen_spk_in)


    """## Utilidad: extracción de matrices de pesos"""

    def get_weights(pop_pre, pop_post):
        conns = nest.GetConnections(pop_pre, pop_post).get(["source", "target", "weight"])
        conns["senders"] = np.array(conns["source"]) - np.min(conns["source"])
        conns["targets"] = np.array(conns["target"]) - np.min(conns["target"])
        conns["weight_matrix"] = np.zeros((len(pop_post), len(pop_pre)))
        conns["weight_matrix"][conns["targets"], conns["senders"]] = conns["weight"]
        return conns

    """## Simulación"""

    # ====================== SIMULACIÓN ======================
    nest.Simulate(duration["sim"])

    weights_post_train = {
        "in_rec": get_weights(nrns_in, nrns_rec),
        "rec_rec": get_weights(nrns_rec, nrns_rec),
        "rec_out": get_weights(nrns_rec, nrns_out),
    }

    """## Análisis de señales y pérdidas"""

   # ====================== ANÁLISIS (SOLO LETRAS, TRAZOS PEN-UP/DOWN) ======================


    output_dir = "abecedario_outputs"
    os.makedirs(output_dir, exist_ok=True)

    events_mm_out = mm_out.get("events")
    readout_signal = events_mm_out["readout_signal"]
    target_signal  = events_mm_out["target_signal"]
    senders        = events_mm_out["senders"]

    # ---- separar canales por sender-id
    sender_ids = sorted(np.unique(senders))
    readouts = [readout_signal[senders == sid] for sid in sender_ids]
    targets  = [target_signal[senders == sid] for sid in sender_ids]

    # ---- detectar canal pen si existe (binario 0/1); si no, pen=1 todo
    def _detect_pen_channel(_targets):
        best, idx = -1.0, None
        for k in range(len(_targets)):
            v = np.asarray(_targets[k])
            in01 = np.mean((v >= -1e-6) & (v <= 1.0 + 1e-6))
            binish = np.mean(np.isclose(v, 0.0, atol=1e-3) | np.isclose(v, 1.0, atol=1e-3))
            score = 0.7 * binish + 0.3 * in01
            if score > best:
                best, idx = score, k
        return idx

    if len(readouts) >= 3:
        pen_idx = _detect_pen_channel(targets)
        other_idx = [i for i in range(len(readouts)) if i != pen_idx][:2]
        y_pen, t_pen = readouts[pen_idx], targets[pen_idx]
        y_dx,  y_dy  = readouts[other_idx[0]], readouts[other_idx[1]]
        t_dx,  t_dy  = targets[other_idx[0]], targets[other_idx[1]]
        has_pen = True
    else:
        y_dx, y_dy = readouts[0], readouts[1]
        t_dx, t_dy = targets[0], targets[1]
        y_pen = np.ones_like(y_dx)
        t_pen = np.ones_like(t_dx)
        has_pen = False

    seq_len = steps["sequence"]
    n_sequences = n_iter * n_batch

    # ---- pérdida por canal y total
    loss_list = []
    for k in range(len(readouts)):
        err = (readouts[k] - targets[k])**2
        loss_list.append(0.5 * np.add.reduceat(err, np.arange(0, steps["task"], seq_len)))
    loss = np.sum(loss_list, axis=0)

    plt.figure()
    for k, Lk in enumerate(loss_list):
        plt.plot(range(1, len(Lk)+1), Lk, label=f"E{k}", alpha=0.7, ls="--" if k==0 else ":")
    plt.plot(range(1, len(loss)+1), loss, label="E total")
    plt.xlabel("training iteration"); plt.ylabel("loss")
    plt.legend(bbox_to_anchor=(1.01,0.5), loc="center left")
    plt.tight_layout()
    plt.savefig(f"{output_dir}/loss_training.png", dpi=300)
    plt.close()

    # ---- util: partir en trazos contiguos según máscara booleana (pen>=0.5)
    def _segments_from_mask(x, y, mask_bool):
        """Devuelve lista de segmentos (x_seg, y_seg) donde mask_bool es True de forma contigua."""
        segs = []
        if isinstance(mask_bool, slice):
            # sin pen: un solo trazo
            return [(x, y)]
        m = np.asarray(mask_bool, dtype=bool)
        if m.size == 0:
            return segs
        # detecta cambios (False->True y True->False)
        # indices donde empieza o termina un tramo True
        diff = np.diff(m.astype(int), prepend=m[0])
        starts = np.flatnonzero((~m[:-1] & m[1:])) + 1
        ends   = np.flatnonzero((m[:-1] & ~m[1:])) + 1
        # caso si empieza ya en True
        if m[0]:
            starts = np.r_[0, starts]
        # y si termina en True
        if m[-1]:
            ends = np.r_[ends, m.size]
        for s, e in zip(starts, ends):
            if e > s:
                segs.append((x[s:e], y[s:e]))
        return segs

    # ---- letras por secuencia (guardado en la creación de inputs)
    letras_por_secuencia = np.load("output_estilos/letras_estilos_por_secuencia.npy")[:, 0]
    letras_unicas = sorted(np.unique(letras_por_secuencia))

    # ---- MSE global (en pen-down si existe)
    if has_pen:
        m_global = (t_pen >= 0.5)
        mse_global_x = mean_squared_error(t_dx[m_global], y_dx[m_global]) if np.any(m_global) else mean_squared_error(t_dx, y_dx)
        mse_global_y = mean_squared_error(t_dy[m_global], y_dy[m_global]) if np.any(m_global) else mean_squared_error(t_dy, y_dy)
    else:
        mse_global_x = mean_squared_error(t_dx, y_dx)
        mse_global_y = mean_squared_error(t_dy, y_dy)
    print(f"📈 MSE GLOBAL -> X:{mse_global_x:.6f}  Y:{mse_global_y:.6f}  Promedio:{0.5*(mse_global_x+mse_global_y):.6f}")
    # ---- figuras y MSE por letra (dibujando por trazos)
    for letra_idx in letras_unicas:
        nombre_base = os.path.splitext(trayectorias[letra_idx])[0]
        idxs = np.where(letras_por_secuencia == letra_idx)[0]
        if idxs.size == 0:
            continue
        last_idx = idxs[-1]
        start = last_idx * seq_len
        end   = start + seq_len

        # señales de la letra
        rdx = y_dx[start:end]; rdy = -y_dy[start:end]
        tdx = t_dx[start:end]; tdy = -t_dy[start:end]
        mR  = (y_pen[start:end] >= 0.5) if has_pen else slice(None)
        mT  = (t_pen[start:end] >= 0.5) if has_pen else slice(None)

        # MSE en pen-down (si no hay, usa todo)
        m_eval = mT if (has_pen and np.any(mT)) else slice(None)
        mse_x = mean_squared_error(t_dx[start:end][m_eval], y_dx[start:end][m_eval])
        mse_y = mean_squared_error(t_dy[start:end][m_eval], y_dy[start:end][m_eval])
        print(f"   Letra {nombre_base}: MSE_X={mse_x:.6f}  MSE_Y={mse_y:.6f}  Promedio={(mse_x+mse_y)/2:.6f}")

        # ---- plot por trazos
        fig, ax = plt.subplots(figsize=(6, 3))
        target_color = "tab:blue"
        readout_color = "tab:red"
        # TARGET: trazos pen-down en azul
        for xs, ys in _segments_from_mask(tdx, tdy, mT):
            ax.plot(xs, ys, color=target_color, label="target pen-down", alpha=0.85)

        # READOUT: trazos pen-down en rojo
        for xs, ys in _segments_from_mask(rdx, rdy, mR):
            ax.plot(xs, ys, color=readout_color, label="readout pen-down", linewidth=1)
        nombre_base = os.path.splitext(trayectorias[letra_idx])[0]
        ax.set_title(f"Letra {nombre_base}")
        ax.axis("equal"); ax.axis("off")
        # evitar duplicar leyendas por múltiples segmentos
        handles, labels = ax.get_legend_handles_labels()
        bylab = dict(zip(labels, handles))
        ax.legend(bylab.values(), bylab.keys(), loc="lower right", fontsize=8)
        plt.tight_layout()
        plt.savefig(f"{output_dir}/{nombre_base}.png", dpi=300)
        plt.close()

    # ---- mosaico del abecedario (solo pen-down para claridad)
    def _label_from_nombre_base(raw_name: str) -> str:
        """
        Devuelve una etiqueta de texto robusta a partir del nombre base del archivo.
        - Si raw_name es 'a' => 'a'
        - Si raw_name es '97' => 'a' (97 = 'a' en ASCII/Unicode básico)
        - En cualquier otro caso => raw_name tal cual
        """
        raw_name = str(raw_name)
        # Caso más común: ya es una letra única
        if len(raw_name) == 1:
            return raw_name
        # Si es un número (p.ej. '97'), intenta convertir a chr()
        try:
            codepoint = int(raw_name)
            return chr(codepoint)
        except Exception:
            # Si no se puede convertir, muestra el texto tal cual
            return raw_name

    espacio_horizontal = 1.2
    fig, ax = plt.subplots(figsize=(14, 6))

    for col, letra_idx in enumerate(letras_unicas):
        # nombre base del fichero de la letra
        nombre_base = os.path.splitext(trayectorias[letra_idx])[0]
        label_text = _label_from_nombre_base(nombre_base)

        # todas las ocurrencias de esa letra en el dataset de secuencias
        idxs = np.where(letras_por_secuencia == letra_idx)[0]
        if idxs.size == 0:
            continue

        # tomamos la última aparición para representar
        last_idx = idxs[-1]
        start = last_idx * seq_len
        end   = start + seq_len

        # offset horizontal en función de la columna (columna = posición 0..N-1)
        offset = col * espacio_horizontal

        # señales con offset (x) y volteo (y) para dibujar como antes
        rdx = y_dx[start:end] + offset
        rdy = -y_dy[start:end]
        tdx = t_dx[start:end] + offset
        tdy = -t_dy[start:end]

        mR  = (y_pen[start:end] >= 0.5) if has_pen else slice(None)
        mT  = (t_pen[start:end] >= 0.5) if has_pen else slice(None)

        # target (azul) y readout (rojo) solo en pen-down
        for xs, ys in _segments_from_mask(tdx, tdy, mT):
            ax.plot(xs, ys, color="blue", alpha=0.6)
        for xs, ys in _segments_from_mask(rdx, rdy, mR):
            ax.plot(xs, ys, color="red", alpha=0.85)

        # etiqueta debajo (o en y=0) del offset actual
        ax.text(offset, 0.0, label_text, fontsize=10, weight="bold",
                ha="center", va="top")

    ax.set_title("Abecedario (pen-down por trazos)")
    ax.axis("equal"); ax.axis("off")
    plt.tight_layout()
    plt.savefig(f"{output_dir}/abecedario_mosaico.png", dpi=300)
    plt.close()



    # ====================== GUARDAR MODELO Y VISUALIZACIONES ======================
    output_folder = "Abcedario"
    os.makedirs(output_folder, exist_ok=True)

    modelo = {
        "pesos_in_rec": weights_post_train["in_rec"]["weight_matrix"],
        "pesos_rec_rec": weights_post_train["rec_rec"]["weight_matrix"],
        "pesos_rec_out": weights_post_train["rec_out"]["weight_matrix"],
        "n_in": n_in,
        "n_rec": n_rec,
        "n_out": n_out,
        "duration": duration,
        "steps": steps,
    }
    ruta_modelo = "Abcedario/modelo_abecedario.pkl"
    with open(ruta_modelo, "wb") as f:
        pickle.dump(modelo, f)
    print(f"✅ Modelo guardado en: {ruta_modelo}")

   